# Generated by Django 5.2.6 on 2025-09-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mosque_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
