# Generated by Django 5.2.6 on 2025-10-17 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='institute',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
