# Generated by Django 5.2.6 on 2025-09-13 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_mosque_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
