# Generated by Django 5.2.7 on 2026-05-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_token_version_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='study',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
