# Generated by Django 5.2.7 on 2026-05-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_study_and_age_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='certificates',
            field=models.TextField(blank=True, null=True),
        ),
    ]
