# Generated by Django 5.2.7 on 2026-05-17 08:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0004_student_is_deleted_student_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='HadithSabr',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hadith_type', models.CharField(choices=[('الأربعين النووية', 'الأربعين النووية')], max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hadith_sabr_entries', to='students.student')),
            ],
            options={
                'db_table': 'hadith_sabr',
            },
        ),
    ]
