# Generated by Django 5.2.7 on 2026-05-17 13:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadith', '0001_initial'),
        ('students', '0004_student_is_deleted_student_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='HadithHifz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_hadith', models.PositiveIntegerField(default=1)),
                ('end_hadith', models.PositiveIntegerField(default=1)),
                ('label', models.CharField(choices=[('حفظ', 'حفظ'), ('مراجعة', 'مراجعة'), ('تثبيت', 'تثبيت')], default='حفظ', max_length=16)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hadith_hifz_entries', to='students.student')),
            ],
            options={
                'db_table': 'hadith_hifz',
                'indexes': [models.Index(fields=['student'], name='hadith_hifz_student_c92a3b_idx')],
            },
        ),
    ]
