# Generated by Django 5.2.7 on 2026-05-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadith', '0002_hadithhifz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hadithhifz',
            name='end_hadith',
        ),
        migrations.RemoveField(
            model_name='hadithhifz',
            name='start_hadith',
        ),
        migrations.AddField(
            model_name='hadithhifz',
            name='hadith_numbers',
            field=models.JSONField(default=list),
        ),
    ]
