# Generated by Django 5.2.6 on 2025-10-20 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('arName', models.CharField(blank=True, max_length=100)),
                ('number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('arName', models.CharField(blank=True, max_length=100)),
                ('number', models.PositiveIntegerField()),
                ('parts', models.ManyToManyField(related_name='chapters', to='quran.part')),
            ],
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verses', to='quran.chapter')),
            ],
            options={
                'ordering': ['chapter_id', 'number'],
                'unique_together': {('chapter', 'number')},
            },
        ),
    ]
