# Generated by Django 5.2.6 on 2025-10-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verse',
            options={'ordering': ['chapter_id', 'index']},
        ),
        migrations.RenameField(
            model_name='chapter',
            old_name='arName',
            new_name='arTitle',
        ),
        migrations.RenameField(
            model_name='chapter',
            old_name='number',
            new_name='index',
        ),
        migrations.RenameField(
            model_name='chapter',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='part',
            old_name='arName',
            new_name='arTitle',
        ),
        migrations.RenameField(
            model_name='part',
            old_name='number',
            new_name='index',
        ),
        migrations.RenameField(
            model_name='part',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='verse',
            old_name='number',
            new_name='index',
        ),
        migrations.AlterUniqueTogether(
            name='verse',
            unique_together={('chapter', 'index')},
        ),
        migrations.AddField(
            model_name='chapter',
            name='totalVerses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='verse',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
