# Generated by Django 5.2.6 on 2025-10-21 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0002_alter_verse_options_rename_arname_chapter_artitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verse',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verses', to='quran.part'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='index',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='index',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
