# Generated by Django 5.2.6 on 2025-10-22 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0003_verse_part_alter_chapter_index_alter_part_index'),
        ('students', '0003_alter_student_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentHifz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_verse', models.PositiveIntegerField(default=1)),
                ('end_verse', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hifz_entries', to='quran.chapter')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hifz_entries', to='students.student')),
            ],
            options={
                'db_table': 'student_hifz',
                'indexes': [models.Index(fields=['student', 'chapter'], name='student_hif_student_e9ba1a_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'chapter', 'start_verse', 'end_verse'), name='Exact chapter and verses range per student')],
            },
        ),
    ]
