# Generated by Django 5.2.7 on 2026-04-20 19:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0004_studenthifz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenthifz',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
