# Generated by Django 5.2.7 on 2026-05-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0005_alter_studenthifz_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenthifz',
            name='mode',
            field=models.CharField(choices=[('memorization', 'Memorization'), ('repetition', 'Repetition'), ('improvement', 'Improvement')], default='memorization', max_length=20),
        ),
    ]
