# Generated by Django 5.2.7 on 2026-05-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0005_studenthifz_is_deleted_studenthifz_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenthifz',
            name='label',
            field=models.CharField(choices=[('حفظ', 'حفظ'), ('مراجعة', 'مراجعة'), ('تثبيت', 'تثبيت')], default='حفظ', max_length=16),
        ),
    ]
