# Generated by Django 5.2.7 on 2026-05-09 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0006_studenthifz_label'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studenthifz',
            name='Exact chapter and verses range per student',
        ),
    ]
