# Generated by Django 5.2.7 on 2026-05-17 08:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0007_remove_unique_constraint_student_hifz'),
        ('students', '0004_student_is_deleted_student_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='HadithSabr',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hadith_type', models.CharField(choices=[('الأربعين النووية', 'الأربعين النووية')], max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hadith_sabr_entries', to='students.student')),
            ],
            options={
                'db_table': 'hadith_sabr',
            },
        ),
        migrations.CreateModel(
            name='QuranSabr',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sabr_type', models.CharField(choices=[('سبر الأوقاف', 'سبر الأوقاف'), ('سبر المعهد', 'سبر المعهد'), ('سبر المعهد التراكمي', 'سبر المعهد التراكمي')], max_length=50)),
                ('range_start', models.PositiveIntegerField()),
                ('range_end', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quran_sabr_entries', to='students.student')),
            ],
            options={
                'db_table': 'quran_sabr',
            },
        ),
    ]
