# Generated by Django 5.2.7 on 2026-05-17 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0008_hadithsabr_quransabr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HadithSabr',
        ),
    ]
