# Generated by Django 5.2.7 on 2026-06-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0009_delete_hadithsabr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenthifz',
            name='label',
            field=models.CharField(choices=[('حفظ', 'حفظ'), ('مراجعة', 'مراجعة'), ('تثبيت', 'تثبيت'), ('حفظ سابق', 'حفظ سابق')], default='حفظ', max_length=16),
        ),
    ]
