# Generated by Django 5.2.7 on 2026-07-01 04:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0010_alter_studenthifz_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHifz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_verse', models.PositiveIntegerField(default=1)),
                ('end_verse', models.PositiveIntegerField(default=1)),
                ('label', models.CharField(choices=[('حفظ', 'حفظ'), ('مراجعة', 'مراجعة'), ('تثبيت', 'تثبيت'), ('حفظ سابق', 'حفظ سابق')], default='حفظ', max_length=16)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_hifz_entries', to='quran.chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hifz_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_hifz',
                'indexes': [models.Index(fields=['user', 'chapter'], name='user_hifz_user_id_d10856_idx')],
            },
        ),
    ]
