# Generated by Django 5.2.7 on 2026-05-07 16:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
        ('lessons', '0002_alter_attendance_unique_together_attendance_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habit',
            name='minusPoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='habit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studentpoints',
            name='isMinus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentpoints',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentpoints',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_points', to='lessons.lesson'),
        ),
        migrations.AddField(
            model_name='studentpoints',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studentpoints',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
