# Generated by Django 5.2.7 on 2026-04-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='minusPoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentpoints',
            name='isMinus',
            field=models.BooleanField(default=False),
        ),
    ]
