# Generated by Django 5.2.7 on 2026-05-11 20:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_habit_is_deleted_habit_minuspoints_habit_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpoints',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
