# Generated by Django 5.2.7 on 2026-06-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_add_date_field_to_studentpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='allowNegative',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habit',
            name='oncePerDay',
            field=models.BooleanField(default=False),
        ),
    ]
