### REGISTER USER

POST http://localhost:8080/api/users
Content-Type: application/json

{
  "name": "Suhail",
  "lastName": "Fares",
  "username": "suhail123",
  "birthday": "2001-07-15",
  "email": "suhail@example.com",
  "password": "securePassword123",
  "role": "STUDENT"
}
